### ISSUE TITLE
後台修正 0225

### ISSUE THREAD

**Issue by ausir0726** [finpo/degi-api#1]
backend

- [x] 口味沒有設定上下架功能
- [x] 後台上傳圖片的地方，應該標示該圖片建議尺寸。
- [x] 公司會員管理 改名 批量會員管理
- [x] 公司訂單管理 改名 批量訂單管理
- [x] 虛擬 ATM 功能
- [ ] 批量會員管理增加三個功能
    i. 檢視該批量會員的每個月的總採購金額。
    ii. 檢視該批量會員的每個月的訂單清單。
    iii. 匯出該批量會員會員的月結單。 ( 客戶1月初補格式 )
- [ ] 批量訂單管理增加兩個功能
    i. 列印該訂單的出貨單 (點陣式印表機)。( 客戶1月初補格式 )
    ii. 清單 應該多一欄 "公司名稱"
- [x] 全站變數增加 訂購單檔案上傳。
- [x] 商品關連只顯示 25 筆

**Comment by joanne3634** [comment]
// 我先把我現在的進度記錄一下 
口味沒有設定上下架功能
公司會員管理 改名 批量會員管理
公司訂單管理 改名 批量訂單管理
虛擬atm < 成立新訂單串接 前台api回傳新增 data['atm_code']> 
購物完成通知信 
批量會員管理 i. 檢視該批量會員的每個月的總採購金額。ii. 檢視該批量會員的每個月的訂單清單。 
批量訂單管理 ii. 清單 應該多一欄 "公司名稱"
全站變數增加 訂購單檔案上傳。
前台全站變數訂購單下載已完成

**Comment by joanne3634** [comment]
// 紀錄一下有改到的code 
[ Qtace ]  
Database 
system_variable ADD formal_title ( for print title )

[Target]
< Database > // extjs 只能改成float 
  bulk_purchase_item (bpi_sprice) float 
  bulk_purchase_order_main (bpom_subtotal, bpom_total) float 
  system_variable ADD formal_title ( for print title )

  js / model / BPOrderModel.js bpom_subtotal 51 
  js / view / BPOrderGridPanel.js 
  js / view / BPOrderWindow.js  
  js / view / CMPointWindow.js  
  js / view / OrderGridPanel.js 
  js / view / GroupOrderWindow.js 
  js / store/ GroupOrderArrayStore.js

 Administrator / model / Order.php 
 Administrator / model / BPOrder.php 

< 列印完成部分 > 
單筆訂單 ( 個人 Ｖ/ 批量 V )
查詢結果總表 ( 個人 V / 批量 V ) // 出貨統計 
月結 ( 批量 V ) // 同查詢結果總表 若輸入公司編號查詢 列印會出現該公司資料 

< 黑貓尚未完成 > 
問一下 黑貓的收件地址是parse過的 
拆成 縣市 鄉鎮市區 村里 鄰 路街 段 巷 弄 號 樓 
這有什麼好寫法嗎? 
還是可以直接填地址不管他？

**Comment by joanne3634** [comment]
得記 商品建議尺寸改完了 
ifWindow.js 168 
IndexSlideGridPanel.js 118 
PopularItemGridPanel.js 139 
NewsGridPanel.js 125
StoreGridPanel.js 124 
FoodGridPanel.js 118  

得記只剩黑貓貨運 
想問地址parse的問題

**Comment by joanne3634** [comment]
黑貓貨運也好了 得記都完成了噢! 
OrderGridPanel.js
BPOrderGridPanel.js 
BPOrder.php

**Comment by ausir0726** [comment]
thanks for all
