### ISSUE TITLE
設計調整

### ISSUE THREAD

**Issue by ausir0726** [finpo/degi-api#2]
- [x] 批量採購單價 「整數」修改為「double」
說明
======
客戶反應批量採購時，產品的單價會設定到小數點，例如 8.17 元
待補充....

**Comment by joanne3634** [comment]
所以是產品訂價還是int 
是批量會員管理 可訂購商品的 商品優惠價 改成 double?

**Comment by ausir0726** [comment]
對，只有批量改成有小數點，但是因為還要計算稅金
目前我還在跟客戶確認

**Comment by joanne3634** [comment]
現在先改批量的總金額跟商品單價 改成float 但之後可能要再加上稅金 
現在都沒有稅金相關的資料 列印的部分那邊之後稅金也要改 
< Database > // extjs 只能改成float 
  bulk_purchase_item (bpi_sprice) float 
  bulk_purchase_order_main (bpom_subtotal, bpom_total) float 
  js / model / BPOrderModel.js bpom_subtotal 51

**Comment by ausir0726** [comment]
hold 先上線 b2c 後再修正。
