### ISSUE TITLE
後台 0420

### ISSUE THREAD

**Issue by ausir0726** [finpo/degi-api#3]
圖片說明請參閱  得記 0416.docx
文件上傳 Chatwork

- [x] 分類缺少說明文字欄位與修改欄位 參閱文件 （12）
- [x] 運費金額計算有錯誤，不管怎麼買都是 270 參閱文件（14）及 得記運費規則.txt
- [x] 運費大圖放入全站變數管理（上傳圖檔）  參閱文件（15）
- [x] YAHOO 收到的信是亂碼 參閱文件（16）
- [x] 後台分類與產品增加軟刪除 （delete flag）刪除前需提示確認，以及確定所有的產品都已刪除 參閱文件（19）
- [x] 分類以及產品，設定下架，前台資料仍會出現 參閱文件（20）

**Comment by ausir0726** [comment]
還沒正式發佈前，不需要更新檔案 list
謝謝

**Comment by joanne3634** [comment]
更新list是什麼意思？

**Comment by ausir0726** [comment]
就是你改了哪些檔案
因為都還在自己的 server 所以我不需要逐檔檢查
（不過比較好的作法應該是不要有 hardcore ，我可以整包上傳）
例如不可以寫道絕對路徑.... 之類的

**Comment by joanne3634** [comment]
都改完了 以下是筆記可忽略 
** 產品取消分頁（直接單頁顯示設 99999 即可）參閱文件 （2）**
從前臺limit 變成 99999即可 
** 商品相關順序不要變 ( 6 ) **
/degi-api/target-local/public/f/item_info/:if_id
relate 固定且包含本身 
** 分類缺少說明文字欄位與修改欄位 參閱文件 （12）**
資料庫 
item_categorty add ( ic_description )
system_variable add ( outside_cate_description , storeside_cate_description )      
後台 ui 
add ic_description 增加欄位 
change item_window , item_category_window textfield -> textareafield // textfield 會置中 textarea是正常area 
前台 api
/degi-api/target-local/public/f/item_category 新增 ic_description 欄位  
// 所有商品 ( -1 , -2 ) 把 宅配商品 跟 店面商品 的 所有商品描述 放到 sv 變數好了
** 運費金額計算有錯誤，不管怎麼買都是 270 參閱文件（14）及 得記運費規則.txt ** 
資料庫
system_variable add point_percent 
Administrator / Order.php 
原本點數計算是寫死的 0.03 移到全站變數 
change function [ insert ] 
** 運費大圖放入全站變數管理（上傳圖檔） 參閱文件（15）** 
資料庫 
system_variable add ( fee_explanation )
Application / System_variable.php
add fee_explanation 換成檔案連結 
** YAHOO 收到的信是亂碼 參閱文件（16）**
有改編碼code 但其實沒有用// 因為hinet預設問題  
請對方改編碼 
** 後台分類與產品增加軟刪除 （delete flag）刪除前需提示確認，以及確定所有的產品都已刪除 參閱文件（19）** 
MyViewpanel 邊欄選單改autoscroll
熱銷商品 
f 
check im_status
b 
check im_status        
改順序 先宅配後店面 order 
選擇商品 商品api不要顯示下架商品 pageSize: 99999
改商品大圖大小 
button 開啟下架
商品管理 
b
配送方式 宅配? 
api default 隱藏下架 button 開啟下架 
       商品口味
下架 // 前台不顯示 改 if_status 刪除 
            刪除 
商品分類管理 
        b
api default 隱藏下架 button 開啟下架 
        商品分類選取商品
刪除 
下架商品/ 修改中的下架  檢查 if_id if_status 商品下口味 都已下架 或是 刪除？ 
停用種類/ 修改中的停用  檢查 im_status 商品都已下架 或是 與商品連結都已刪除？ 
** 分類以及產品，設定下架，前台資料仍會出現 參閱文件（20）** 
ItemInfo.php ItemList.php fixed
