### ISSUE TITLE
功能性調整 0430

### ISSUE THREAD

**Issue by ausir0726** [finpo/degi-api#5]
- [x] 產品說明原設定再產品，要更改到口味，不同口味設定不同的文案
- [x] 上述修改前台 API 回傳資訊，看是否有影響到資料名稱

需要再 5/7 - 5/8 前
謝謝

**Comment by joanne3634** [comment]
改完了 
** Application / API ** 
ItemInfo.php
** BackendUI **
ifArrayStore.js
ItemWindow.js 
ifWindow.js 
ifsubWindow.js

**Comment by ausir0726** [comment]
感謝
