### ISSUE TITLE
0508 後台補充調整

### ISSUE THREAD

**Issue by ausir0726** [finpo/degi-api#7]
參閱 chatwork 文件 德記20150507.docx

- [x] 訂單更改處理中，跳出視窗帶一個日曆，選取預計出貨日，更改出貨日期，出貨後改出貨當天日期。（閱3）
- [x] 出貨寄送出貨通知信件 （已上傳 chatwork）
- [x] Email 寄出寄件者請用  target.bakery@msa.hinet.net  得記食品有限公司 （但你在 c9 應該看不出來，但是要加上去）

以上，謝謝。

**Comment by ausir0726** [comment]
@joanne3634 出貨通知文案已上傳 chatwork

**Comment by joanne3634** [comment]
都好了噢
__Administrator / API __
Order.php 
MessagePlugin.php
ItemMainController.php 
__BackendUI__ 
OrderGridPanel.js
